# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Update API docker image

on:
  push:
    branches:
    - main
    paths:
    - 'src/**'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Clean the repo
      run: rm -rf spring-api-portfolio/

    - name: Import Repo
      run: git clone https://github.com/smarsou/spring-api-portfolio.git

    - name: Update permissions
      run: cd spring-api-portfolio/ && chmod 777 mvnw

    - name: Build the jar file
      run: cd spring-api-portfolio/ && ./mvnw package

    - name: Update docker image
      run: cd spring-api-portfolio/ && sudo docker build --build-arg JAR_FILE=target/*.jar -t smarsou/api .

    - name: Clean code
      run: rm -rf spring-api-portfolio/
